In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
cd /content/drive/My Drive/Tesis1-DanielChapi-Documentos/HistoricalData-StockMarketIndices

/content/drive/My Drive/Tesis1-DanielChapi-Documentos/HistoricalData-StockMarketIndices

In [0]:
!ls

 Alemania.csv	 DJI.csv       ReinoUnido.csv
 Argentina.csv	 España.csv    SP500.csv
 Australia.csv	 Francia.csv  'Stock Markets Closing times .gsheet'
 Brasil.csv	 India.csv     WorldStockIndices.csv
 Chile.csv	 Japon.csv     WorldStockIndices_discrete.csv
 China.csv	 Lima.csv
 Cobre.csv	 Mexico.csv

# Obtencion de datos

In [0]:
import pandas_datareader as pdr
import datetime 

start = datetime.datetime(2000, 3, 30)
end = datetime.datetime.now()
#Peru PEN
SPBLPGPT = pdr.get_data_yahoo('^SPBLPGPT',start,end)
#Brasil BRL
BVSP = pdr.get_data_yahoo('^BVSP',start,end) 
#Chile
IPSA = pdr.get_data_yahoo('^IPSA',start,end) 
#Argentina USD
MERV  = pdr.get_data_yahoo('^MERV',start,end) 
#Mexico
MXX = pdr.get_data_yahoo('^MXX',start,end) 
#USA S&P 500 
GSPC = pdr.get_data_yahoo('^GSPC',start,end) 
#USA Dow Jones Industrial 500
DJI = pdr.get_data_yahoo('^DJI',start,end) 
#Paris CAC
FCHI = pdr.get_data_yahoo('^FCHI',start,end) 
#Alemania DAX
GDAXI = pdr.get_data_yahoo('^GDAXI',start,end) 
#Japon Nikkei225
N225 = pdr.get_data_yahoo('^N225',start,end) 
#China Hang Seng Index Hong Kong
HSI = pdr.get_data_yahoo('^HSI',start,end) 
#India SENSEX
SENSEX = pdr.get_data_yahoo('^BSESN',start,end)
#Australia S&P/ASX200
ASX200= pdr.get_data_yahoo('^AXJO',start,end)
#UK FTSE
FTSE = pdr.get_data_yahoo('%5EFTSE%3FP%3D%5EFTSE',start,end) 
#Copper May 20 Future HG=F
COPPER = pdr.get_data_yahoo('HG=F',start,end)
#España ^IBEX
IBEX = pdr.get_data_yahoo('^IBEX',start,end)

/usr/local/lib/python3.6/dist-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [0]:
COPPER

              High     Low    Open   Close      Volume  Adj Close
Date
2000-03-30  0.8070  0.8025  0.8035  0.8025       351.0     0.8025
2000-03-31  0.8005  0.7975  0.7975  0.8000       437.0     0.8000
2000-04-03  0.7975  0.7865  0.7910  0.7975       439.0     0.7975
2000-04-04  0.7895  0.7890  0.7895  0.7890       159.0     0.7890
2000-04-05  0.7890  0.7865  0.7890  0.7865       211.0     0.7865
...            ...     ...     ...     ...         ...        ...
2020-04-13  2.3525  2.3015  2.3240  2.3185  31949049.0     2.3185
2020-04-14  2.3355  2.3080  2.3280  2.3260  29089419.0     2.3260
2020-04-15  2.3295  2.2770  2.3250  2.2935  23717676.0     2.2935
2020-04-16  2.3580  2.2890  2.2975  2.3260  18333470.0     2.3260
2020-04-17  2.3575  2.3315  2.3440  2.3395  30624644.0     2.3395

[5048 rows x 6 columns]

In [0]:

Indices=[SPBLPGPT,BVSP,IPSA,MERV,MXX,GSPC,DJI,FCHI,GDAXI,N225,HSI,SENSEX,ASX200,FTSE,COPPER,IBEX]

In [0]:
Indices[0].to_csv('Lima.csv')
Indices[1].to_csv('Brasil.csv')
Indices[2].to_csv('Chile.csv')
Indices[3].to_csv('Argentina.csv')
Indices[4].to_csv('Mexico.csv')
Indices[5].to_csv('SP500.csv')
Indices[6].to_csv('DJI.csv')
Indices[7].to_csv('Francia.csv')
Indices[8].to_csv('Alemania.csv')
Indices[9].to_csv('Japon.csv')
Indices[10].to_csv('China.csv')
Indices[11].to_csv('India.csv')
Indices[13].to_csv('Australia.csv')
Indices[12].to_csv('ReinoUnido.csv')
Indices[14].to_csv('Cobre.csv')
Indices[15].to_csv('España.csv')

#Preprocesamiento

In [0]:
import pandas as pd
Indices=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
Indices[0] = pd.read_csv('Mexico.csv', header=0, index_col='Date', parse_dates=True)
Indices[1] = pd.read_csv('Lima.csv', header=0, index_col='Date', parse_dates=True)
Indices[2] = pd.read_csv('Brasil.csv', header=0, index_col='Date', parse_dates=True)
Indices[3] = pd.read_csv('Chile.csv', header=0, index_col='Date', parse_dates=True)
Indices[4] = pd.read_csv('Argentina.csv', header=0, index_col='Date', parse_dates=True)
Indices[5] = pd.read_csv('DJI.csv', header=0, index_col='Date', parse_dates=True)
Indices[6] = pd.read_csv('SP500.csv', header=0, index_col='Date', parse_dates=True)
Indices[7] = pd.read_csv('Francia.csv', header=0, index_col='Date', parse_dates=True)
Indices[8] = pd.read_csv('ReinoUnido.csv', header=0, index_col='Date', parse_dates=True)
Indices[9] = pd.read_csv('Alemania.csv', header=0, index_col='Date', parse_dates=True)
Indices[10] = pd.read_csv('India.csv', header=0, index_col='Date', parse_dates=True)
Indices[11] = pd.read_csv('China.csv', header=0, index_col='Date', parse_dates=True)
Indices[12] = pd.read_csv('Japon.csv', header=0, index_col='Date', parse_dates=True)
Indices[13] = pd.read_csv('Australia.csv', header=0, index_col='Date', parse_dates=True)
Indices[14] = pd.read_csv('Cobre.csv', header=0, index_col='Date', parse_dates=True)
Indices[15] = pd.read_csv('España.csv', header=0, index_col='Date', parse_dates=True)

In [0]:
Indices[14]

              High     Low    Open   Close      Volume  Adj Close
Date
2000-03-30  0.8070  0.8025  0.8035  0.8025       351.0     0.8025
2000-03-31  0.8005  0.7975  0.7975  0.8000       437.0     0.8000
2000-04-03  0.7975  0.7865  0.7910  0.7975       439.0     0.7975
2000-04-04  0.7895  0.7890  0.7895  0.7890       159.0     0.7890
2000-04-05  0.7890  0.7865  0.7890  0.7865       211.0     0.7865
...            ...     ...     ...     ...         ...        ...
2020-04-13  2.3525  2.3015  2.3240  2.3185  31949049.0     2.3185
2020-04-14  2.3355  2.3080  2.3280  2.3260  29089419.0     2.3260
2020-04-15  2.3295  2.2770  2.3250  2.2935  23717676.0     2.2935
2020-04-16  2.3580  2.2890  2.2975  2.3260  18333470.0     2.3260
2020-04-17  2.3575  2.3315  2.3440  2.3395  30624644.0     2.3395

[5048 rows x 6 columns]

In [0]:
#Se filtran las columnas innecesarias para el modelo
openLima=pd.DataFrame(Indices[1]["Open"])
for i in range(len(Indices)):
  Indices[i]=Indices[i].drop(['High','Low','Open','Volume','Adj Close'],axis=1)
  #print(Indices[i].index[0])

In [0]:
openLima

                    Open
Date
2000-03-30   1661.170044
2000-03-31   1655.739990
2000-04-03   1664.739990
2000-04-04   1654.640015
2000-04-05   1645.579956
...                  ...
2020-04-13  13899.809570
2020-04-14  14336.950195
2020-04-15  14535.099609
2020-04-16  14493.419922
2020-04-17  14446.940430

[4869 rows x 1 columns]

In [0]:
#Juntamos todos los csvs en un solo dataframe donde cada columna es un Indice diferente
#y cada fila son los valores de los indices en una fecha

df=pd.DataFrame()
for i in range(len(Indices)):
  #skip Chile because of invalid date range
  if i==3: 
    continue
  df=pd.concat([df,Indices[i]], join='outer', axis=1)
df=pd.concat([df,openLima],join='outer',axis=1)

In [0]:
#Nombramos las columnas respecto a la region de cada indice
df.columns=['Mexico','Lima','Brasil','Argentina','DJI','SP500','Francia','ReinoUnido','Alemania','India','China','Japon','Australia','Cobre','España','LimaOpen']

In [0]:
#savepoint
df.to_csv('WorldStockIndices.csv')

In [0]:
df

                  Mexico          Lima  ...        España      LimaOpen
Date                                    ...
2000-03-30   7604.490234   1655.500000  ...  11833.400391   1661.170044
2000-03-31   7473.250000   1663.069946  ...  11935.000000   1655.739990
2000-04-03   7378.819824   1654.619995  ...  11686.400391   1664.739990
2000-04-04   7194.830078   1644.380005  ...  11584.200195   1654.640015
2000-04-05   7272.839844   1674.000000  ...  11374.599609   1645.579956
...                  ...           ...  ...           ...           ...
2020-04-13  34613.671875  14379.820312  ...           NaN  13899.809570
2020-04-14  34746.390625  14464.820312  ...   7108.600098  14336.950195
2020-04-15  33855.238281  14456.950195  ...   6839.500000  14535.099609
2020-04-16  33759.750000  14446.730469  ...   6763.399902  14493.419922
2020-04-17  34743.101562  14493.950195  ...   6875.799805  14446.940430

[5711 rows x 16 columns]

In [0]:
df = pd.read_csv('WorldStockIndices.csv', header=0, index_col='Date', parse_dates=True)

### MySQL Loading dataset to database

In [0]:
!pip install pymysql

Collecting pymysql
  Downloading https://files.pythonhosted.org/packages/ed/39/15045ae46f2a123019aa968dfcba0396c161c20f855f11dea6796bcaae95/PyMySQL-0.9.3-py2.py3-none-any.whl (47kB)
     |████████████████████████████████| 51kB 1.7MB/s
Installing collected packages: pymysql
Successfully installed pymysql-0.9.3

In [0]:
import pymysql
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://Chaps:dejarhuella12@chaps-1.ckzdev3xn88t.us-east-2.rds.amazonaws.com:3306/tesis')

In [0]:
df.to_sql(con=engine, name='indices', if_exists='replace')

In [0]:
pd.read_sql('select * from indices;', con=engine)

           Date        Mexico          Lima  ...   Cobre        España      LimaOpen
0    2000-03-30   7604.490234   1655.500000  ...  0.8025  11833.400391   1661.170044
1    2000-03-31   7473.250000   1663.069946  ...  0.8000  11935.000000   1655.739990
2    2000-04-03   7378.819824   1654.619995  ...  0.7975  11686.400391   1664.739990
3    2000-04-04   7194.830078   1644.380005  ...  0.7890  11584.200195   1654.640015
4    2000-04-05   7272.839844   1674.000000  ...  0.7865  11374.599609   1645.579956
...         ...           ...           ...  ...     ...           ...           ...
5688 2020-04-13  34613.671875  14379.820312  ...  2.3185           NaN  13899.809570
5689 2020-04-14  34746.390625  14464.820312  ...  2.3260   7108.600098  14336.950195
5690 2020-04-15  33855.238281  14456.950195  ...  2.2935   6839.500000  14535.099609
5691 2020-04-16  33759.750000  14446.730469  ...  2.3290   6763.399902  14493.419922
5692 2020-04-17  34743.101562  14493.950195  ...  2.3395   6875.799805  14446.940430

[5693 rows x 16 columns]

### Eliminamos los registros con algun indice nulo

In [0]:
df = df.dropna(axis=0)
df.sort_index(inplace=True, ascending=False)

In [0]:
df

                    Lima    Brasil  ...  UnitedKingdom    Australia
Date                                ...
2020-02-19  19728.320312  116518.0  ...    7162.500000  7457.000000
2020-02-18  19600.060547  114977.0  ...    7144.600098  7382.000000
2020-02-13  20008.029297  115662.0  ...    7130.200195  7452.000000
2020-02-12  20059.310547  116674.0  ...    7103.200195  7534.399902
2020-02-10  19941.390625  112570.0  ...    7055.299805  7446.899902
...                  ...       ...  ...            ...          ...
2000-01-12   1818.859985   16617.0  ...    3078.899902  6532.799805
2000-01-11   1803.709961   16573.0  ...    3088.399902  6518.899902
2000-01-06   1798.300049   16107.0  ...    3023.399902  6447.200195
2000-01-05   1810.150024   16245.0  ...    2999.300049  6535.899902
2000-01-04   1811.800049   15851.0  ...    3018.699951  6665.899902

[3421 rows x 13 columns]

### Transformamos los indices a valores discretos donde: 
####  0=disminucion del indice respecto a la fecha anterior
####  1=aumento del indice respecto a la fecha anterior
####  2=no hubo variacion

In [0]:
#0 ha disminuido
#1 ha aumentado
#2 se ha mantenido igual
rowAnt= df.loc[df.index[0]]
indexAnt=df.index[0]
for index, row in df.iterrows():
  if index==df.index[0]:
    continue
  for column in df.columns:
    if row[column]>rowAnt[column]:
      df.at[indexAnt,column] = 0
    elif row[column]<rowAnt[column]:
      df.at[indexAnt,column] = 1
    elif row[column]==rowAnt[column]:
      df.at[indexAnt,column] = 2
  indexAnt=index
  rowAnt=row

In [0]:
df
#la fecha mas antigua no se transformo por no tener una fecha inmediata anterior a comparar

                   Lima   Brasil  ...  UnitedKingdom    Australia
Date                              ...
2020-02-19     1.000000      1.0  ...       1.000000     1.000000
2020-02-18     0.000000      0.0  ...       1.000000     0.000000
2020-02-13     0.000000      0.0  ...       1.000000     0.000000
2020-02-12     1.000000      1.0  ...       1.000000     1.000000
2020-02-10     0.000000      0.0  ...       1.000000     0.000000
...                 ...      ...  ...            ...          ...
2000-01-12     1.000000      1.0  ...       0.000000     1.000000
2000-01-11     1.000000      1.0  ...       1.000000     1.000000
2000-01-06     0.000000      0.0  ...       1.000000     0.000000
2000-01-05     0.000000      1.0  ...       0.000000     0.000000
2000-01-04  1811.800049  15851.0  ...    3018.699951  6665.899902

[3421 rows x 13 columns]

In [0]:
#savepoint
df.to_csv('WorldStockIndices_discrete.csv')